# Generated by Django 3.1.2 on 2020-10-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Customer',
            fields=[
                ('Sl_No', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=25)),
                ('Account_No', models.IntegerField()),
                ('Photo', models.ImageField(upload_to='media')),
                ('Aadhar_No', models.CharField(max_length=12)),
                ('Phone_No', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('Sl_No', 'Account_No')},
            },
        ),
    ]
