# Generated by Django 3.1.2 on 2020-10-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_customer',
            name='Account_No',
            field=models.IntegerField(editable=False),
        ),
    ]
