# Generated by Django 3.1.2 on 2020-10-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20201025_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_customer',
            name='Account_No',
            field=models.CharField(editable=False, max_length=13),
        ),
    ]
