# Generated by Django 3.1.2 on 2020-10-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20201025_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chit_Batches',
            fields=[
                ('Sl_No', models.AutoField(primary_key=True, serialize=False)),
                ('Batch_No', models.IntegerField()),
                ('Total_Fund', models.IntegerField()),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Number_of_Customers', models.IntegerField()),
                ('Status', models.BooleanField()),
            ],
        ),
    ]
