# Generated by Django 3.1.2 on 2020-10-28 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_chit_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_customer',
            name='Aadhar_No',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterUniqueTogether(
            name='chit_batches',
            unique_together={('Sl_No', 'Batch_No')},
        ),
        migrations.CreateModel(
            name='Savings_Customer',
            fields=[
                ('Sl_No', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Added', models.DateField()),
                ('Name', models.CharField(max_length=25)),
                ('Total_Savings', models.IntegerField()),
                ('Account_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.all_customer')),
            ],
        ),
        migrations.CreateModel(
            name='Credit_Customer',
            fields=[
                ('Sl_No', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Credited', models.DateField()),
                ('Name', models.CharField(max_length=25)),
                ('Interest_Rate', models.CharField(max_length=5)),
                ('Total_Credit', models.IntegerField()),
                ('Account_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.all_customer')),
            ],
        ),
        migrations.CreateModel(
            name='Chit_Fund_Customer',
            fields=[
                ('Sl_No', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Credited', models.DateField()),
                ('Name', models.CharField(max_length=25)),
                ('Account_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.all_customer')),
                ('Batch_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.chit_batches')),
            ],
        ),
        migrations.CreateModel(
            name='Savings_Customer_Savings',
            fields=[
                ('Sl_No', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=25)),
                ('Amount', models.IntegerField()),
                ('Account_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.all_customer')),
            ],
            options={
                'unique_together': {('Sl_No', 'Amount')},
            },
        ),
    ]
