# Generated by Django 3.1.2 on 2020-10-28 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20201028_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings_customer_savings',
            old_name='Amount',
            new_name='Amount_Deposited',
        ),
        migrations.AlterField(
            model_name='savings_customer',
            name='Total_Savings',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='savings_customer_savings',
            unique_together={('Sl_No', 'Amount_Deposited')},
        ),
        migrations.CreateModel(
            name='Credit_Customer_Credit',
            fields=[
                ('Sl_No', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=25)),
                ('Amount_Credited', models.IntegerField()),
                ('Account_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.all_customer')),
            ],
            options={
                'unique_together': {('Sl_No', 'Amount_Credited')},
            },
        ),
    ]
