# Generated by Django 3.1.2 on 2020-10-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20201028_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings_customer',
            name='Total_Savings',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
