# Generated by Django 3.1.2 on 2020-10-31 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20201030_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Savings_Customer',
        ),
    ]
