# Generated by Django 3.1.2 on 2020-10-31 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_delete_savings_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving_Customer',
            fields=[
                ('Sl_No', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Credited', models.DateField()),
                ('Name', models.CharField(max_length=25)),
                ('Total_Savings', models.IntegerField()),
                ('Account_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.all_customer')),
            ],
        ),
    ]
